services:
  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/library/jasper-app:latest
    container_name: jasper-app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/jasper

volumes:
  postgres-data:
